# Generated by Django 4.2 on 2024-12-11 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Назавание завода', max_length=150, verbose_name='Название')),
                ('email', models.CharField(help_text='Электронная почта завода', max_length=150, verbose_name='Электронная почта')),
                ('country', models.CharField(help_text='Страна, где расположен завод', max_length=150, verbose_name='Страна')),
                ('city', models.CharField(help_text='Город, где расположен завод', max_length=150, verbose_name='Город')),
                ('street', models.CharField(help_text='Улица, где расположен завод', max_length=150, verbose_name='Улица')),
                ('house_number', models.CharField(help_text='Номер дома, где расположен завод', max_length=50, verbose_name='Номер дома')),
                ('product_name', models.CharField(blank=True, help_text='Назавание продукта завода', max_length=150, null=True, verbose_name='Продукт')),
                ('product_model', models.CharField(blank=True, help_text='Модель продукта завода', max_length=150, null=True, verbose_name='Модель продукта')),
                ('product_date', models.DateField(blank=True, help_text='Дата выхода продукта завода', max_length=50, null=True, verbose_name='Дата выхода продукта')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания записи о заводе')),
            ],
            options={
                'verbose_name': 'Завод',
                'verbose_name_plural': 'Заводы',
            },
        ),
        migrations.CreateModel(
            name='RetailChain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Назавание розничной сети', max_length=150, verbose_name='Название')),
                ('email', models.CharField(help_text='Электронная почта розничной сети', max_length=150, verbose_name='Электронная почта')),
                ('country', models.CharField(help_text='Страна, где расположена розничная сеть', max_length=150, verbose_name='Страна')),
                ('city', models.CharField(help_text='Город, где расположена розничная сеть', max_length=150, verbose_name='Город')),
                ('street', models.CharField(help_text='Улица, где расположена розничная сеть', max_length=150, verbose_name='Улица')),
                ('house_number', models.CharField(help_text='Номер дома, где расположена розничная сеть', max_length=50, verbose_name='Номер дома')),
                ('product_name', models.CharField(blank=True, help_text='Назавание продукта розничной сети', max_length=150, null=True, verbose_name='Продукт')),
                ('product_model', models.CharField(blank=True, help_text='Модель продукта розничной сети', max_length=150, null=True, verbose_name='Модель продукта')),
                ('product_date', models.DateField(blank=True, help_text='Дата выхода продукта розничной сети', max_length=50, null=True, verbose_name='Дата выхода продукта')),
                ('provider_dept', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания записи о розничной сети')),
                ('provider_factory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='electronics_network.factory', verbose_name='Завод-поставщик')),
            ],
            options={
                'verbose_name': 'Розничная сеть',
                'verbose_name_plural': 'Розничные сети',
            },
        ),
        migrations.CreateModel(
            name='Entrepreneur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Назавание индивидуального предпринимателя', max_length=150, verbose_name='Название')),
                ('email', models.CharField(help_text='Электронная почта индивидуального предпринимателя', max_length=150, verbose_name='Электронная почта')),
                ('country', models.CharField(help_text='Страна, где расположен индивидуальный предприниматель', max_length=150, verbose_name='Страна')),
                ('city', models.CharField(help_text='Город, где расположен индивидуальный предприниматель', max_length=150, verbose_name='Город')),
                ('street', models.CharField(help_text='Улица, где расположен индивидуальный предприниматель', max_length=150, verbose_name='Улица')),
                ('house_number', models.CharField(help_text='Номер дома, где расположен индивидуальный предприниматель', max_length=50, verbose_name='Номер дома')),
                ('product_name', models.CharField(blank=True, help_text='Назавание продукта индивидуального предпринимателя', max_length=150, null=True, verbose_name='Продукт')),
                ('product_model', models.CharField(blank=True, help_text='Модель продукта индивидуального предпринимателя', max_length=150, null=True, verbose_name='Модель продукта')),
                ('product_date', models.DateField(blank=True, help_text='Дата выхода продукта индивидуального предпринимателя', max_length=50, null=True, verbose_name='Дата выхода продукта')),
                ('provider_dept', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания записи об индивидуальном предпринимателе')),
                ('provider_factory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='electronics_network.factory', verbose_name='Завод-поставщик')),
                ('provider_retail_chain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='electronics_network.retailchain', verbose_name='Розничная сеть-поставщик')),
            ],
            options={
                'verbose_name': 'Индивидуальный предприниматель',
                'verbose_name_plural': 'Индивидуальные предприниматели',
            },
        ),
    ]
