# Generated by Django 4.2 on 2024-12-16 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('electronics_network', '0002_alter_entrepreneur_provider_dept_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrepreneur',
            name='provider_entrepreneur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='electronics_network.entrepreneur', verbose_name='Поставщик ИП'),
        ),
        migrations.AddField(
            model_name='factory',
            name='provider_dept',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Задолженность перед поставщиком', max_digits=20, null=True, verbose_name='Задолженность'),
        ),
        migrations.AddField(
            model_name='factory',
            name='provider_factory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='electronics_network.factory', verbose_name='Поставщик'),
        ),
        migrations.AddField(
            model_name='retailchain',
            name='provider_retail_chain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='electronics_network.retailchain', verbose_name='Поставщик-розница'),
        ),
        migrations.AlterField(
            model_name='entrepreneur',
            name='provider_factory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='electronics_network.factory', verbose_name='Поставщик-завод'),
        ),
        migrations.AlterField(
            model_name='entrepreneur',
            name='provider_retail_chain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='electronics_network.retailchain', verbose_name='Поставщик-розница'),
        ),
        migrations.AlterField(
            model_name='retailchain',
            name='provider_factory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='electronics_network.factory', verbose_name='Поставщик-завод'),
        ),
    ]
