# Generated by Django 4.2 on 2024-12-16 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronics_network', '0003_entrepreneur_provider_entrepreneur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrepreneur',
            name='provider_dept',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Задолженность перед поставщиком', max_digits=20, null=True, verbose_name='Задолженность'),
        ),
        migrations.AlterField(
            model_name='factory',
            name='provider_dept',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Задолженность перед поставщиком', max_digits=20, null=True, verbose_name='Задолженность'),
        ),
        migrations.AlterField(
            model_name='retailchain',
            name='provider_dept',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Задолженность перед поставщиком', max_digits=20, null=True, verbose_name='Задолженность'),
        ),
    ]
